import { Console } from "@/types";

export const consoles: Console[] = [
  {
    id: "c1",
    name: "PlayStation 5 — Unit A",
    type: "PS5",
    description:
      "Experience next-gen gaming with lightning-fast load times, stunning 4K visuals, and the immersive DualSense controller. Perfect for solo adventures or co-op sessions.",
    specs: ["4K HDR", "120fps", "DualSense Controller", "825GB SSD"],
    includedGames: ["Spider-Man 2", "God of War Ragnarök", "Gran Turismo 7", "FC 25"],
    pricePerHour: 25000,
    pricePerDay: 150000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&h=400&fit=crop",
    totalBookings: 142,
  },
  {
    id: "c2",
    name: "PlayStation 5 — Unit B",
    type: "PS5",
    description:
      "A second PS5 station with the full next-gen experience. Ideal when Unit A is booked — same specs, same epic gameplay.",
    specs: ["4K HDR", "120fps", "DualSense Controller", "1TB SSD"],
    includedGames: ["Final Fantasy XVI", "Horizon Forbidden West", "Demon's Souls"],
    pricePerHour: 25000,
    pricePerDay: 150000,
    status: "rented",
    imageUrl: "https://images.unsplash.com/photo-1612287230202-22b6b2f7e7b0?w=600&h=400&fit=crop",
    totalBookings: 98,
  },
  {
    id: "c3",
    name: "PlayStation 4 Pro — Unit A",
    type: "PS4",
    description:
      "A classic powerhouse with an extensive game library. Great for retro favorites and budget-friendly gaming sessions.",
    specs: ["4K Upscaled", "HDR", "DualShock 4", "1TB HDD"],
    includedGames: ["The Last of Us Part II", "Ghost of Tsushima", "Uncharted 4"],
    pricePerHour: 15000,
    pricePerDay: 90000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1486401897018-50576f7f4f69?w=600&h=400&fit=crop",
    totalBookings: 210,
  },
  {
    id: "c4",
    name: "Xbox Series X — Unit A",
    type: "Xbox Series X",
    description:
      "The most powerful Xbox ever. 12 teraflops of raw power for true 4K gaming with Game Pass titles ready to play.",
    specs: ["4K Native", "120fps", "Xbox Wireless Controller", "1TB SSD"],
    includedGames: ["Halo Infinite", "Forza Horizon 5", "Starfield"],
    pricePerHour: 25000,
    pricePerDay: 150000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600&h=400&fit=crop",
    totalBookings: 87,
  },
  {
    id: "c5",
    name: "Xbox Series S — Unit A",
    type: "Xbox Series S",
    description:
      "Compact next-gen gaming at an accessible price. Digital-only with quick resume and smooth 1440p performance.",
    specs: ["1440p", "120fps", "Xbox Wireless Controller", "512GB SSD"],
    includedGames: ["Minecraft", "Sea of Thieves", "Gears 5"],
    pricePerHour: 18000,
    pricePerDay: 110000,
    status: "maintenance",
    imageUrl: "https://images.unsplash.com/photo-1630328888234-e06b55e05e40?w=600&h=400&fit=crop",
    totalBookings: 65,
  },
  {
    id: "c6",
    name: "Nintendo Switch — Unit A",
    type: "Nintendo Switch",
    description:
      "Grab a Joy-Con and dive into Nintendo's legendary library. Perfect for party games and family-friendly fun.",
    specs: ["1080p Docked", "Joy-Con Controllers", "Portable Mode", "32GB Storage"],
    includedGames: ["Mario Kart 8 Deluxe", "Super Smash Bros. Ultimate", "Zelda: TOTK"],
    pricePerHour: 20000,
    pricePerDay: 120000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600&h=400&fit=crop",
    totalBookings: 175,
  },
  {
    id: "c7",
    name: "Nintendo Switch OLED — Unit B",
    type: "Nintendo Switch",
    description:
      "Vibrant OLED screen for handheld play. The ultimate Switch experience for solo sessions on the go or docked.",
    specs: ["OLED Display", "Joy-Con Controllers", "64GB Storage", "Enhanced Audio"],
    includedGames: ["Animal Crossing", "Splatoon 3", "Pokémon Scarlet"],
    pricePerHour: 22000,
    pricePerDay: 130000,
    status: "rented",
    imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=400&fit=crop",
    totalBookings: 112,
  },
  {
    id: "c8",
    name: "PC Gaming Rig — Unit A",
    type: "PC Gaming",
    description:
      "High-end gaming PC with RTX graphics. Play the latest AAA titles at max settings with a mechanical keyboard and gaming mouse included.",
    specs: ["RTX 4070", "32GB RAM", "240Hz Monitor", "Mechanical Keyboard"],
    includedGames: ["Cyberpunk 2077", "Elden Ring", "Baldur's Gate 3", "CS2"],
    pricePerHour: 35000,
    pricePerDay: 200000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600&h=400&fit=crop",
    totalBookings: 156,
  },
  {
    id: "c9",
    name: "PC Gaming Rig — Unit B",
    type: "PC Gaming",
    description:
      "Streamer-ready setup with dual monitors and a quality mic. Stream your sessions or grind ranked matches in style.",
    specs: ["RTX 4060", "16GB RAM", "Dual Monitors", "Streaming Mic"],
    includedGames: ["Valorant", "League of Legends", "Dota 2"],
    pricePerHour: 30000,
    pricePerDay: 180000,
    status: "available",
    imageUrl: "https://images.unsplash.com/photo-1547084470-4c4d98d92d12?w=600&h=400&fit=crop",
    totalBookings: 89,
  },
  {
    id: "c10",
    name: "PlayStation 4 Slim — Unit B",
    type: "PS4",
    description:
      "Reliable PS4 Slim for casual sessions. Huge back-catalog of hits at a wallet-friendly hourly rate.",
    specs: ["1080p", "HDR", "DualShock 4", "500GB HDD"],
    includedGames: ["Red Dead Redemption 2", "Bloodborne", "Persona 5 Royal"],
    pricePerHour: 12000,
    pricePerDay: 75000,
    status: "maintenance",
    imageUrl: "https://images.unsplash.com/photo-1493710339155-6ceb8a7a0f0e?w=600&h=400&fit=crop",
    totalBookings: 134,
  },
];
